title: Bryn Malan # your name (or website title) here
logo: "/images/images/IMG_2051.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analytics Enthusiast
  <a href="https://https://www.linkedin.com/in/bryn-malan-7791a3183//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
